MvcCoreConciertos/Models/Categoria.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcCoreConciertos.Models
{
    public class Categoria
    {
        public int IdCategoria { get; set; }
        public string Nombre { get; set; }
    }
}

MvcCoreConciertos/Models/ErrorViewModel.cs
namespace MvcCoreConciertos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreConciertos/Models/Evento.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcCoreConciertos.Models
{
    public class Evento
    {
        public int IdEvento { get; set; }
        public string Nombre { get; set; }
        public string Artista { get; set; }
        public int IdCategoria { get; set; }
        public string Imagen { get; set; }
    }
}

MvcCoreConciertos/Models/KeysModel.cs
namespace MvcCoreConciertos.Models
{
    public class keysModel
    {
        public string MySql { get; set; }
        public string ApiConciertos { get; set; }
        public string BucketName { get; set; }
        public string BucketUrl { get; set; }
    }
}

MvcCoreConciertos/Controllers/ConciertosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreConciertos.Models;
using MvcCoreConciertos.Services;

namespace MvcCoreConciertos.Controllers
{
    public class ConciertosController : Controller
    {
        private ServiceConciertos service;

        public ConciertosController(ServiceConciertos service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            List<Evento> eventos = await this.service.GetEventosAsync();
            ViewData["categorias"] = await this.service.GetCategoriaAsync();
            return View(eventos);
        }

        [HttpPost]
        public async Task<IActionResult> Index(int idcategoria)
        {
            List<Evento> evenosFiltered = await this.service.GetEventosByCategoriaAsync(idcategoria);
            ViewData["categorias"] = await this.service.GetCategoriaAsync();
            return View(evenosFiltered);

        }
    }
}

MvcCoreConciertos/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreConciertos.Models;
using System.Diagnostics;

namespace MvcCoreConciertos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreConciertos/Views/Conciertos/Index.cshtml
@model IEnumerable<MvcCoreConciertos.Models.Evento>

@{
    ViewData["Title"] = "Index";
    List<Categoria> categorias = ViewData["categorias"] as List<Categoria>;
    string urlsBucket = keys.BucketUrl;
}

<h1>Index</h1>
@if (categorias != null)
{
    <form class="row" method="post">
        <div class="col-md-9">
            <select name="idcategoria" class="form-control">
                @foreach (Categoria ct in categorias)
                {
                    <option value="@ct.IdCategoria">@ct.Nombre</option>
                }
            </select>
        </div>
        <div class="col-md-3">
            <button class="btn btn-outline-dark">
                filtrar
            </button>
        </div>
    </form>
}

@if (Model != null)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.IdEvento)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Artista)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IdCategoria)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Imagen)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdEvento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Artista)
                    </td>
                    <td>
                        @{
                            var categoria = categorias.FirstOrDefault(x => x.IdCategoria == item.IdCategoria); 
                        }

                        @Html.DisplayFor(modelItem => categoria.Nombre)
                        
                    </td>
                    <td>
                        <img src="@(urlsBucket+item.Imagen)" alt="@item.Nombre" width="150px" height="150pxs" />
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

MvcCoreConciertos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCoreConciertos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreConciertos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreConciertos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreConciertos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Conciertos" asp-action="Index">Conciertos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcCoreConciertos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>